apiVersion: v1
kind: Service
metadata:
  namespace: cloud-cells
  annotations:
  labels:
    app: cloud-cells
  name: cloud-cells
spec:
  ports:    
  type: NodePort  
  ports:
  - port: 8888
    protocol: TCP
    name: http 
    
  selector:
    app: cloud-cells
status:
  loadBalancer: {}
